### ISSUE TITLE
Bubble bottom bar using dart packages

### ISSUE THREAD

**Issue by supriya-045** [opencodeiiita/Coder-Queen#13]
Use this in pubspec.yaml
dependencies:
  bubble_bottom_bar: ^1.2.0

By using this update active icon for home ,search and bookmark.

do this by creating a new` hom.dart` file .

**Comment by mansigautam777** [comment]
claim

**Comment by isharawat** [comment]
Claim

**Comment by Anushka1309** [comment]
claim
