### ISSUE TITLE
Create convex bottom navigation bar

### ISSUE THREAD

**Issue by supriya-045** [opencodeiiita/Coder-Queen#14]
Icons to be included:
1. Home 
2. Discovery
3. Add
4. Message
5. Profile

This should be created in a new convex.dart

**Comment by Monik09** [comment]
claim

**Comment by supriya-045** [comment]
> claim

This is girls only repository . Please find issues in other repositories except Coder-queen.

**Comment by Monik09** [comment]
ohh  sorry.

**Comment by isharawat** [comment]
Claim

**Comment by medhatiwari** [comment]
claim

**Comment by Anushka1309** [comment]
claim

**Comment by AnushaNathRoy** [comment]
claim

**Comment by supriya-045** [comment]
> Claim


it has been 2 days ,when u are going to make PR do it fast..
