### ISSUE TITLE
Bottom Navigation bar flutter 1

### ISSUE THREAD

**Issue by supriya-045** [opencodeiiita/Coder-Queen#3]
Create a dart file for home like "home.dart" there & it would return scaffold.
Navigation bar should contains :
1.  A home icon
2. Search icon

**Comment by sanjay395** [comment]
claim

**Comment by saloni33** [comment]
claim

**Comment by isharawat** [comment]
I can solve this issue. please assign it to me

**Comment by Anushka1309** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by Kavita-Dhamot** [comment]
claim

**Comment by Mantraraj8472** [comment]
Want to claim
