### ISSUE TITLE
fetch the category wise news from newsapi 

### ISSUE THREAD

**Issue by supriya-045** [opencodeiiita/Coder-Queen#47]
You have to fetch newsa data from newsapi.org according to category and it should display on homepage.

**Comment by supriya-045** [comment]
> claim

Its been 2 days , how much of you completed it?

**Comment by KIRTEE-TECH** [comment]
claim

**Comment by medhatiwari** [comment]
> > claim
> 
> Its been more than 2 days , how much of you completed it?

I will try to do it before 8pm today. Please extend the time till then
